# Generated by Django 2.1.5 on 2019-01-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alter',
            name='B',
        ),
        migrations.RemoveField(
            model_name='alter',
            name='C',
        ),
        migrations.RemoveField(
            model_name='alter',
            name='D',
        ),
    ]
