# Generated by Django 2.1.5 on 2019-01-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_auto_20190122_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='question',
        ),
    ]
