# Generated by Django 2.1.5 on 2019-01-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0004_auto_20190122_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter',
            name='A',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alter',
            name='B',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alter',
            name='C',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alter',
            name='D',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alter',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='enquete.Pergunta'),
        ),
    ]
