# Generated by Django 2.1.5 on 2019-01-23 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0005_auto_20190122_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alter', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='alter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='votos',
        ),
        migrations.DeleteModel(
            name='alter',
        ),
        migrations.AddField(
            model_name='opcoes',
            name='pergunta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='enquete.Pergunta'),
        ),
    ]
