# Generated by Django 2.1.5 on 2019-01-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0007_auto_20190123_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='opcoes',
            name='pergunta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enquete.Pergunta'),
        ),
        migrations.AddField(
            model_name='teste',
            name='opcoes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enquete.opcoes'),
        ),
        migrations.AddField(
            model_name='teste',
            name='pergunta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enquete.Pergunta'),
        ),
    ]
