# Generated by Django 2.1.5 on 2019-01-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0008_auto_20190124_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='opcoes',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='teste',
        ),
    ]
