# Generated by Django 2.1.5 on 2019-01-25 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0009_auto_20190124_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcoes',
            name='imagens',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='opcoes',
            name='pergunta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='enquete.Pergunta'),
        ),
    ]
