# Generated by Django 2.1.5 on 2019-01-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0011_auto_20190125_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
